---
- name: Demo on ios_config
  hosts: CSR1
  gather_facts: false
  tasks:
    - name: Demo on backup
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          dir_path: "/tmp/config_backup/"
          filename: "{{ inventory_hostname }}_config_{{ lookup('pipe', 'date +%d-%m-%Y-%H%M%S') }}.cfg"
      register: output

    - name: Display output
      ansible.builtin.debug:
        msg: "{{ output }}"
