---
- name: Demo on ios_config
  hosts: ciscoVIOS
  gather_facts: false
  tasks:
    - name: Configure Interface
      cisco.ios.ios_config:
        lines:
          - description Configured using Ansible Automation Platform
        parents:
          - interface GigabitEthernet0/1
      register: output
    
    - name: Display output
      ansible.builtin.debug:
        msg: "{{ output }}"
