---
- name: Demo on Service Now
  hosts: CSR1
  gather_facts: false
  tasks:
    - name: Run Cisco Command
      cisco.ios.ios_command:
        commands:
          - show ip int br
      register: output

    - name: Create work Notes
      ansible.builtin.set_fact:
        show_command: "{{ output.stdout }}"

    # - name: Send to template
    #   ansible.builtin.set_fact:
    #     snow_update: "{{ lookup('template', 'demo.j2') }}"
    #   vars:
    #     heading: "{{ ansible_play_name }}"

    - name: Slack update
      ansible.builtin.include_tasks: 08_snow_notifications.yaml

    # - name: Update SNOW Ticket
    #   servicenow.servicenow.snow_record:
    #     username: admin
    #     password: /W1gsooCFT*2
    #     instance: dev283883
    #     state: present
    #     number: INC0010001
    #     data:
    #       work_notes: "{{ snow_update }}"
    #   register: snow_output
    #   delegate_to: localhost

    # - name: Display output
    #   ansible.builtin.debug:
    #     var: snow_output
